name: release

on:
  push:
    branches: [ master, actions ]
#  push:
#    tags:
#      - "*"

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.15.6'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build UI
        run:  cd ui && yarn install && yarn build

      - name: Release dry run
        run: make release-dry-run-snapshot

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env

      - name: Release publish
        run: make release-snapshot
